/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ridwan
 */
public class kalkulator extends javax.swing.JFrame {
    
    String angka;
    double jumlah, angka1, angka2;
    int pilih;
    
    /**
     * Creates new form kalkulator
     */
    public kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        layar = new javax.swing.JTextField();
        btnbagi = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnkali = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        btnangka0 = new javax.swing.JButton();
        btnangka7 = new javax.swing.JButton();
        btnangka8 = new javax.swing.JButton();
        btnangka9 = new javax.swing.JButton();
        btnkurang = new javax.swing.JButton();
        btnangka4 = new javax.swing.JButton();
        btnangka5 = new javax.swing.JButton();
        btnangka6 = new javax.swing.JButton();
        btnsamadengan = new javax.swing.JButton();
        btnangka1 = new javax.swing.JButton();
        btnangka2 = new javax.swing.JButton();
        btnangka3 = new javax.swing.JButton();
        btnkoma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        layar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layarActionPerformed(evt);
            }
        });
        getContentPane().add(layar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 70));

        btnbagi.setText("/");
        btnbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbagiActionPerformed(evt);
            }
        });
        getContentPane().add(btnbagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 50, 40));

        btnclear.setText("C");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, 40));

        btnkali.setText("x");
        btnkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkali, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 50, 40));

        btntambah.setText("+");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        getContentPane().add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 50, 40));

        btnangka0.setText("0");
        btnangka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka0ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 170, 40));

        btnangka7.setText("7");
        btnangka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, 40));

        btnangka8.setText("8");
        btnangka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 50, 40));

        btnangka9.setText("9");
        btnangka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka9ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 50, 40));

        btnkurang.setText("-");
        btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangActionPerformed(evt);
            }
        });
        getContentPane().add(btnkurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 50, 40));

        btnangka4.setText("4");
        btnangka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 40));

        btnangka5.setText("5");
        btnangka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 50, 40));

        btnangka6.setText("6");
        btnangka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 50, 40));

        btnsamadengan.setText("=");
        btnsamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsamadenganActionPerformed(evt);
            }
        });
        getContentPane().add(btnsamadengan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 50, 90));

        btnangka1.setText("1");
        btnangka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 50, 40));

        btnangka2.setText("2");
        btnangka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 50, 40));

        btnangka3.setText("3");
        btnangka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 50, 40));

        btnkoma.setText(".");
        btnkoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkomaActionPerformed(evt);
            }
        });
        getContentPane().add(btnkoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 50, 40));

        pack();
    }// </editor-fold>                        

    private void btnangka0ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(angka==null){
            angka = "0";
        }
        else {
            angka +="0";
        }
        layar.setText(angka);
    }                                         

    private void btnangka7ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(angka==null){
            angka = "7";
        }
        else {
            angka +="7";
        }
        layar.setText(angka);
    }                                         

    private void btnangka8ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(angka==null){
            angka = "8";
        }
        else {
            angka +="8";
        }
        layar.setText(angka);
    }                                         

    private void btnangka9ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(angka==null){
            angka = "9";
        }
        else {
            angka +="9";
        }
        layar.setText(angka);
    }                                         

    private void btnkurangActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        layar.setText("-");
        angka = "";
        pilih = 2;
    }                                         

    private void btnangka4ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(angka==null){
            angka = "4";
        }
        else {
            angka +="4";
        }
        layar.setText(angka);
    }                                         

    private void btnangka5ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(angka==null){
            angka = "5";
        }
        else {
            angka +="5";
        }
        layar.setText(angka);
    }                                         

    private void btnangka6ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(angka==null){
            angka = "6";
        }
        else {
            angka +="6";
        }
        layar.setText(angka);
    }                                         

    private void btnsamadenganActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        switch (pilih){
            case 1 :
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 + angka2;
                angka = Double.toString(jumlah);
                layar.setText(angka);
                break;
            case 2 :
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 - angka2;
                angka = Double.toString(jumlah);
                layar.setText(angka);
                break;
            case 3 :
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 * angka2;
                angka = Double.toString(jumlah);
                layar.setText(angka);
                break;
            case 4 :
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 / angka2;
                angka = Double.toString(jumlah);
                layar.setText(angka);
                break;
        }
    }                                             

    private void btnangka1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(angka==null){
            angka = "1";
        }
        else {
            angka +="1";
        }
        layar.setText(angka);
    }                                         

    private void btnangka2ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(angka==null){
            angka = "2";
        }
        else {
            angka +="2";
        }
        layar.setText(angka);
    }                                         

    private void btnangka3ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(angka==null){
            angka = "3";
        }
        else {
            angka +="3";
        }
        layar.setText(angka);
    }                                         

    private void btnkomaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        angka +=".";
        layar.setText(angka);
    }                                       

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        layar.setText("");
        angka="";
        angka1=0;
        angka2=0;
        jumlah=0;
    }                                        

    private void btnkaliActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        layar.setText("x");
        angka = "";
        pilih = 3;
    }                                       

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        layar.setText("+");
        angka = "";
        pilih = 1;
    }                                         

    private void btnbagiActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        layar.setText("/");
        angka = "";
        pilih = 4;
    }                                       

    private void layarActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnangka0;
    private javax.swing.JButton btnangka1;
    private javax.swing.JButton btnangka2;
    private javax.swing.JButton btnangka3;
    private javax.swing.JButton btnangka4;
    private javax.swing.JButton btnangka5;
    private javax.swing.JButton btnangka6;
    private javax.swing.JButton btnangka7;
    private javax.swing.JButton btnangka8;
    private javax.swing.JButton btnangka9;
    private javax.swing.JButton btnbagi;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnkali;
    private javax.swing.JButton btnkoma;
    private javax.swing.JButton btnkurang;
    private javax.swing.JButton btnsamadengan;
    private javax.swing.JButton btntambah;
    private javax.swing.JTextField layar;
    // End of variables declaration                   
}
